/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { Object3D, AnimationClip, AnimationAction, AnimationMixer } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.SkinnedMesh
    Coat: THREE.SkinnedMesh
    Pants: THREE.SkinnedMesh
    Shirt: THREE.SkinnedMesh
    Shoe: THREE.SkinnedMesh
    Eyelashes: THREE.SkinnedMesh
    Hair: THREE.SkinnedMesh
    mixamorig4Hips: THREE.Bone
  }
  materials: {
    body: THREE.MeshStandardMaterial
    hair: THREE.MeshStandardMaterial
  }
}

type ActionName = 'static' | 'idle' | 'walking' | 'leftTurn' | 'rightTurn'
type GLTFActions = Record<ActionName, THREE.AnimationAction>


type AnimationApi<T = GLTFActions> = {
  ref: React.MutableRefObject<Object3D | undefined | null>;
  clips: AnimationClip[];
  mixer: AnimationMixer;
  names: string[];
  actions: T;
};


type AnimationControllerProps = {
  modelRef: React.MutableRefObject<THREE.Group | undefined | null>
  animationApi: AnimationApi
}

export const AnimationController = ({modelRef, animationApi}: AnimationControllerProps): null => {

  const { ref, clips, mixer, names, actions } = animationApi; 

  React.useEffect(() => {
    actions.walking.play()
  }, [actions])

  return null
}



const Model = (props: JSX.IntrinsicElements['group']): JSX.Element => {
  const groupRef = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/Player.glb') as GLTFResult
  const animationApi: AnimationApi = useAnimations<GLTFActions>(animations, groupRef)

  return (
    <>
    <AnimationController modelRef={groupRef} animationApi={animationApi}/>
    <group ref={groupRef} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Player"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
          userData={{ name: 'Player' }}>
          <primitive object={nodes.mixamorig4Hips} />
          <skinnedMesh
            name="Body"
            geometry={nodes.Body.geometry}
            material={nodes.Body.material}
            skeleton={nodes.Body.skeleton}
            userData={{ name: 'Body' }}
          />
          <skinnedMesh
            name="Coat"
            geometry={nodes.Coat.geometry}
            material={nodes.Coat.material}
            skeleton={nodes.Coat.skeleton}
            userData={{ name: 'Coat' }}
          />
          <skinnedMesh
            name="Pants"
            geometry={nodes.Pants.geometry}
            material={nodes.Pants.material}
            skeleton={nodes.Pants.skeleton}
            userData={{ name: 'Pants' }}
          />
          <skinnedMesh
            name="Shirt"
            geometry={nodes.Shirt.geometry}
            material={nodes.Shirt.material}
            skeleton={nodes.Shirt.skeleton}
            userData={{ name: 'Shirt' }}
          />
          <skinnedMesh
            name="Shoe"
            geometry={nodes.Shoe.geometry}
            material={nodes.Shoe.material}
            skeleton={nodes.Shoe.skeleton}
            userData={{ name: 'Shoe' }}
          />
          <skinnedMesh
            name="Eyelashes"
            geometry={nodes.Eyelashes.geometry}
            material={nodes.Eyelashes.material}
            skeleton={nodes.Eyelashes.skeleton}
            userData={{ name: 'Eyelashes' }}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={nodes.Hair.material}
            skeleton={nodes.Hair.skeleton}
            userData={{ name: 'Hair' }}
          />
        </group>
        <group
          name="idle"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
          userData={{ name: 'idle' }}>
          <group
            name="mixamorig4Hips_1"
            position={[0.28, 0.44, -94.64]}
            rotation={[-1.59, 0.03, -0.08]}
            userData={{ name: 'mixamorig4:Hips' }}>
            <group
              name="mixamorig4Spine_1"
              position={[0, 9.89, -0.43]}
              rotation={[-0.02, -0.02, 0.04]}
              userData={{ name: 'mixamorig4:Spine' }}>
              <group
                name="mixamorig4Spine1_1"
                position={[0, 11.55, 0]}
                rotation={[0.01, 0, 0.1]}
                scale={[1, 1, 1]}
                userData={{ name: 'mixamorig4:Spine1' }}>
                <group
                  name="mixamorig4Spine2_1"
                  position={[0, 13.2, 0]}
                  rotation={[0.01, 0.01, 0.1]}
                  userData={{ name: 'mixamorig4:Spine2' }}>
                  <group
                    name="mixamorig4Neck_1"
                    position={[0, 14.85, 0]}
                    rotation={[0.06, -0.01, -0.04]}
                    userData={{ name: 'mixamorig4:Neck' }}>
                    <group
                      name="mixamorig4Head_1"
                      position={[0, 7.38, 2.17]}
                      rotation={[0.02, -0.01, -0.04]}
                      userData={{ name: 'mixamorig4:Head' }}>
                      <group
                        name="mixamorig4HeadTop_End_1"
                        position={[0, 21.35, 6.27]}
                        rotation={[0, 0, 0]}
                        userData={{ name: 'mixamorig4:HeadTop_End' }}
                      />
                    </group>
                  </group>
                  <group
                    name="mixamorig4LeftShoulder_1"
                    position={[5.78, 12.84, -0.1]}
                    rotation={[1.73, -0.42, -1.33]}
                    userData={{ name: 'mixamorig4:LeftShoulder' }}>
                    <group
                      name="mixamorig4LeftArm_1"
                      position={[0, 12.24, 0]}
                      rotation={[1.12, -0.05, -0.12]}
                      scale={[1, 1, 1]}
                      userData={{ name: 'mixamorig4:LeftArm' }}>
                      <group
                        name="mixamorig4LeftForeArm_1"
                        position={[0, 20.8, 0]}
                        rotation={[0.01, -0.01, 0.25]}
                        userData={{ name: 'mixamorig4:LeftForeArm' }}>
                        <group
                          name="mixamorig4LeftHand_1"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, -0.45, -0.07]}
                          userData={{ name: 'mixamorig4:LeftHand' }}>
                          <group
                            name="mixamorig4LeftHandThumb1_1"
                            position={[-2.82, 2.86, 1.24]}
                            rotation={[0.18, 0.55, 0.32]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandThumb1' }}>
                            <group
                              name="mixamorig4LeftHandThumb2_1"
                              position={[-0.67, 3.3, 0]}
                              rotation={[0.02, -0.28, -0.26]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandThumb2' }}>
                              <group
                                name="mixamorig4LeftHandThumb3_1"
                                position={[0.15, 3.11, 0]}
                                rotation={[0.01, -0.05, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandThumb3' }}>
                                <group
                                  name="mixamorig4LeftHandThumb4_1"
                                  position={[0.51, 2.54, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandIndex1_1"
                            position={[-3.27, 9.02, 0.08]}
                            rotation={[0.12, 0.01, 0.02]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandIndex1' }}>
                            <group
                              name="mixamorig4LeftHandIndex2_1"
                              position={[0.01, 3.04, 0]}
                              rotation={[0.36, -0.01, -0.05]}
                              userData={{ name: 'mixamorig4:LeftHandIndex2' }}>
                              <group
                                name="mixamorig4LeftHandIndex3_1"
                                position={[0, 2.82, 0]}
                                rotation={[0.18, 0, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandIndex3' }}>
                                <group
                                  name="mixamorig4LeftHandIndex4_1"
                                  position={[0, 2.47, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandMiddle1_1"
                            position={[-0.91, 9.23, -0.15]}
                            rotation={[0.26, 0, -0.06]}
                            userData={{ name: 'mixamorig4:LeftHandMiddle1' }}>
                            <group
                              name="mixamorig4LeftHandMiddle2_1"
                              position={[0, 3.23, 0]}
                              rotation={[0.58, -0.03, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandMiddle2' }}>
                              <group
                                name="mixamorig4LeftHandMiddle3_1"
                                position={[0, 2.98, 0]}
                                rotation={[0.21, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandMiddle3' }}>
                                <group
                                  name="mixamorig4LeftHandMiddle4_1"
                                  position={[0, 2.68, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandRing1_1"
                            position={[1.06, 9.06, -0.13]}
                            rotation={[0.45, -0.01, -0.11]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandRing1' }}>
                            <group
                              name="mixamorig4LeftHandRing2_1"
                              position={[0, 2.78, 0]}
                              rotation={[0.7, -0.02, -0.07]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandRing2' }}>
                              <group
                                name="mixamorig4LeftHandRing3_1"
                                position={[0, 2.68, 0]}
                                rotation={[0.34, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandRing3' }}>
                                <group
                                  name="mixamorig4LeftHandRing4_1"
                                  position={[0, 2.4, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandPinky1_1"
                            position={[3.11, 8.47, 0.1]}
                            rotation={[0.61, -0.03, -0.2]}
                            userData={{ name: 'mixamorig4:LeftHandPinky1' }}>
                            <group
                              name="mixamorig4LeftHandPinky2_1"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, -0.03, -0.07]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandPinky2' }}>
                              <group
                                name="mixamorig4LeftHandPinky3_1"
                                position={[0, 2.07, 0]}
                                rotation={[0.36, -0.01, -0.05]}
                                userData={{ name: 'mixamorig4:LeftHandPinky3' }}>
                                <group
                                  name="mixamorig4LeftHandPinky4_1"
                                  position={[0, 1.76, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="mixamorig4RightShoulder_1"
                    position={[-5.78, 12.84, -0.08]}
                    rotation={[1.67, 0.43, 1.53]}
                    userData={{ name: 'mixamorig4:RightShoulder' }}>
                    <group
                      name="mixamorig4RightArm_1"
                      position={[0, 12.24, 0]}
                      rotation={[0.84, -0.01, 0.01]}
                      userData={{ name: 'mixamorig4:RightArm' }}>
                      <group
                        name="mixamorig4RightForeArm_1"
                        position={[0, 20.81, 0]}
                        rotation={[0.01, 0.01, -0.31]}
                        userData={{ name: 'mixamorig4:RightForeArm' }}>
                        <group
                          name="mixamorig4RightHand_1"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, 0.19, 0.22]}
                          userData={{ name: 'mixamorig4:RightHand' }}>
                          <group
                            name="mixamorig4RightHandThumb1_1"
                            position={[2.77, 2.84, 1.17]}
                            rotation={[0.17, -0.55, -0.32]}
                            userData={{ name: 'mixamorig4:RightHandThumb1' }}>
                            <group
                              name="mixamorig4RightHandThumb2_1"
                              position={[0.65, 3.25, 0]}
                              rotation={[0.02, 0.28, 0.29]}
                              userData={{ name: 'mixamorig4:RightHandThumb2' }}>
                              <group
                                name="mixamorig4RightHandThumb3_1"
                                position={[-0.07, 3.12, 0]}
                                rotation={[0.02, 0.05, -0.06]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandThumb3' }}>
                                <group
                                  name="mixamorig4RightHandThumb4_1"
                                  position={[-0.58, 2.57, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:RightHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandIndex1_1"
                            position={[3.35, 9.01, 0.13]}
                            rotation={[0.11, -0.01, -0.02]}
                            userData={{ name: 'mixamorig4:RightHandIndex1' }}>
                            <group
                              name="mixamorig4RightHandIndex2_1"
                              position={[0, 3.04, 0]}
                              rotation={[0.36, 0.01, 0.05]}
                              userData={{ name: 'mixamorig4:RightHandIndex2' }}>
                              <group
                                name="mixamorig4RightHandIndex3_1"
                                position={[0, 2.8, 0]}
                                rotation={[0.24, 0, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandIndex3' }}>
                                <group
                                  name="mixamorig4RightHandIndex4_1"
                                  position={[0, 2.33, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandMiddle1_1"
                            position={[0.92, 9.25, -0.21]}
                            rotation={[0.25, 0, 0.06]}
                            userData={{ name: 'mixamorig4:RightHandMiddle1' }}>
                            <group
                              name="mixamorig4RightHandMiddle2_1"
                              position={[0, 3.24, 0]}
                              rotation={[0.58, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandMiddle2' }}>
                              <group
                                name="mixamorig4RightHandMiddle3_1"
                                position={[0, 2.99, 0]}
                                rotation={[0.28, 0, 0.03]}
                                userData={{ name: 'mixamorig4:RightHandMiddle3' }}>
                                <group
                                  name="mixamorig4RightHandMiddle4_1"
                                  position={[0, 2.66, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandRing1_1"
                            position={[-1.12, 9.28, -0.05]}
                            rotation={[0.44, 0.01, 0.11]}
                            userData={{ name: 'mixamorig4:RightHandRing1' }}>
                            <group
                              name="mixamorig4RightHandRing2_1"
                              position={[0, 2.71, 0]}
                              rotation={[0.7, 0.02, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandRing2' }}>
                              <group
                                name="mixamorig4RightHandRing3_1"
                                position={[0, 2.57, 0]}
                                rotation={[0.31, 0, 0]}
                                userData={{ name: 'mixamorig4:RightHandRing3' }}>
                                <group
                                  name="mixamorig4RightHandRing4_1"
                                  position={[0, 2.19, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:RightHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandPinky1_1"
                            position={[-3.15, 8.55, 0.1]}
                            rotation={[0.6, 0.03, 0.2]}
                            userData={{ name: 'mixamorig4:RightHandPinky1' }}>
                            <group
                              name="mixamorig4RightHandPinky2_1"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandPinky2' }}>
                              <group
                                name="mixamorig4RightHandPinky3_1"
                                position={[0, 2.04, 0]}
                                rotation={[0.39, 0.01, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandPinky3' }}>
                                <group
                                  name="mixamorig4RightHandPinky4_1"
                                  position={[0, 1.7, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4LeftUpLeg_1"
              position={[9.21, -5.49, -0.52]}
              rotation={[-0.33, 0.19, -2.84]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:LeftUpLeg' }}>
              <group
                name="mixamorig4LeftLeg_1"
                position={[0, 43.52, 0]}
                rotation={[-0.44, -0.16, -0.01]}
                userData={{ name: 'mixamorig4:LeftLeg' }}>
                <group
                  name="mixamorig4LeftFoot_1"
                  position={[-0.14, 36.83, -1.83]}
                  rotation={[1.1, -0.15, 0]}
                  scale={[1, 1, 1]}
                  userData={{ name: 'mixamorig4:LeftFoot' }}>
                  <group
                    name="mixamorig4LeftToeBase_1"
                    position={[0.17, 15.83, -1.68]}
                    rotation={[0.57, -0.03, 0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:LeftToeBase' }}>
                    <group
                      name="mixamorig4LeftToe_End_1"
                      position={[0, 4.95, 0]}
                      rotation={[0, 0, 0]}
                      scale={[1, 1, 1]}
                      userData={{ name: 'mixamorig4:LeftToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4RightUpLeg_1"
              position={[-9.21, -5.49, -0.46]}
              rotation={[0.04, -0.07, -2.97]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:RightUpLeg' }}>
              <group
                name="mixamorig4RightLeg_1"
                position={[0, 43.52, 0]}
                rotation={[-0.13, 0.09, 0.11]}
                scale={[1, 1, 1]}
                userData={{ name: 'mixamorig4:RightLeg' }}>
                <group
                  name="mixamorig4RightFoot_1"
                  position={[0.14, 36.85, -1.52]}
                  rotation={[1.16, -0.2, -0.12]}
                  userData={{ name: 'mixamorig4:RightFoot' }}>
                  <group
                    name="mixamorig4RightToeBase_1"
                    position={[-0.16, 15.71, -1.88]}
                    rotation={[0.57, 0.04, -0.02]}
                    userData={{ name: 'mixamorig4:RightToeBase' }}>
                    <group
                      name="mixamorig4RightToe_End_1"
                      position={[0, 4.89, 0]}
                      rotation={[0, 0, 0]}
                      userData={{ name: 'mixamorig4:RightToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="walking"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
          userData={{ name: 'walking' }}>
          <group
            name="rigHips"
            position={[0.26, 0.41, -95.15]}
            rotation={[-1.58, 0.17, -0.07]}
            userData={{ name: 'rig:Hips' }}>
            <group
              name="rigSpine"
              position={[0, 9.89, -0.43]}
              rotation={[0, -0.01, 0.05]}
              userData={{ name: 'rig:Spine' }}>
              <group
                name="mixamorig4Spine1_2"
                position={[0, 11.55, 0]}
                rotation={[0.03, -0.04, 0.01]}
                scale={[1, 1, 1]}
                userData={{ name: 'mixamorig4:Spine1' }}>
                <group
                  name="mixamorig4Spine2_2"
                  position={[0, 13.2, 0]}
                  rotation={[-0.05, -0.04, 0]}
                  userData={{ name: 'mixamorig4:Spine2' }}>
                  <group
                    name="mixamorig4Neck_2"
                    position={[0, 14.85, 0]}
                    rotation={[-0.02, -0.02, -0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:Neck' }}>
                    <group
                      name="mixamorig4Head_2"
                      position={[0, 7.38, 2.17]}
                      rotation={[0.04, 0, 0.03]}
                      userData={{ name: 'mixamorig4:Head' }}>
                      <group
                        name="mixamorig4HeadTop_End_2"
                        position={[0, 21.35, 6.27]}
                        rotation={[0, 0, 0]}
                        userData={{ name: 'mixamorig4:HeadTop_End' }}
                      />
                    </group>
                  </group>
                  <group
                    name="mixamorig4LeftShoulder_2"
                    position={[5.78, 12.84, -0.1]}
                    rotation={[1.82, -0.28, -1.21]}
                    userData={{ name: 'mixamorig4:LeftShoulder' }}>
                    <group
                      name="mixamorig4LeftArm_2"
                      position={[0, 12.24, 0]}
                      rotation={[1, -0.07, -0.08]}
                      userData={{ name: 'mixamorig4:LeftArm' }}>
                      <group
                        name="mixamorig4LeftForeArm_2"
                        position={[0, 20.8, 0]}
                        rotation={[0.02, 0, 0.63]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'mixamorig4:LeftForeArm' }}>
                        <group
                          name="mixamorig4LeftHand_2"
                          position={[0, 27.54, 0]}
                          rotation={[-0.08, 0.35, 0.28]}
                          userData={{ name: 'mixamorig4:LeftHand' }}>
                          <group
                            name="mixamorig4LeftHandThumb1_2"
                            position={[-2.82, 2.86, 1.24]}
                            rotation={[0.01, 0.71, 0.19]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandThumb1' }}>
                            <group
                              name="mixamorig4LeftHandThumb2_2"
                              position={[-0.67, 3.3, 0]}
                              rotation={[0.17, -0.37, 0.13]}
                              userData={{ name: 'mixamorig4:LeftHandThumb2' }}>
                              <group
                                name="mixamorig4LeftHandThumb3_2"
                                position={[0.15, 3.11, 0]}
                                rotation={[0.06, 0.2, 0.26]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:LeftHandThumb3' }}>
                                <group
                                  name="mixamorig4LeftHandThumb4_2"
                                  position={[0.51, 2.54, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandIndex1_2"
                            position={[-3.27, 9.02, 0.08]}
                            rotation={[-0.09, 0, 0.04]}
                            userData={{ name: 'mixamorig4:LeftHandIndex1' }}>
                            <group
                              name="mixamorig4LeftHandIndex2_2"
                              position={[0.01, 3.04, 0]}
                              rotation={[0.29, -0.01, -0.05]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandIndex2' }}>
                              <group
                                name="mixamorig4LeftHandIndex3_2"
                                position={[0, 2.82, 0]}
                                rotation={[0.07, 0, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:LeftHandIndex3' }}>
                                <group
                                  name="mixamorig4LeftHandIndex4_2"
                                  position={[0, 2.47, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandMiddle1_2"
                            position={[-0.91, 9.23, -0.15]}
                            rotation={[0.27, 0, -0.04]}
                            userData={{ name: 'mixamorig4:LeftHandMiddle1' }}>
                            <group
                              name="mixamorig4LeftHandMiddle2_2"
                              position={[0, 3.23, 0]}
                              rotation={[0.47, -0.02, -0.06]}
                              userData={{ name: 'mixamorig4:LeftHandMiddle2' }}>
                              <group
                                name="mixamorig4LeftHandMiddle3_2"
                                position={[0, 2.98, 0]}
                                rotation={[0.28, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandMiddle3' }}>
                                <group
                                  name="mixamorig4LeftHandMiddle4_2"
                                  position={[0, 2.68, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandRing1_2"
                            position={[1.06, 9.06, -0.13]}
                            rotation={[0.58, -0.01, -0.04]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandRing1' }}>
                            <group
                              name="mixamorig4LeftHandRing2_2"
                              position={[0, 2.78, 0]}
                              rotation={[0.3, 0, -0.03]}
                              userData={{ name: 'mixamorig4:LeftHandRing2' }}>
                              <group
                                name="mixamorig4LeftHandRing3_2"
                                position={[0, 2.68, 0]}
                                rotation={[0.22, 0, -0.02]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:LeftHandRing3' }}>
                                <group
                                  name="mixamorig4LeftHandRing4_2"
                                  position={[0, 2.4, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandPinky1_2"
                            position={[3.11, 8.47, 0.1]}
                            rotation={[0.52, -0.02, -0.15]}
                            userData={{ name: 'mixamorig4:LeftHandPinky1' }}>
                            <group
                              name="mixamorig4LeftHandPinky2_2"
                              position={[0, 2.46, 0]}
                              rotation={[0.51, -0.02, -0.04]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandPinky2' }}>
                              <group
                                name="mixamorig4LeftHandPinky3_2"
                                position={[0, 2.07, 0]}
                                rotation={[0.12, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandPinky3' }}>
                                <group
                                  name="mixamorig4LeftHandPinky4_2"
                                  position={[0, 1.76, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="mixamorig4RightShoulder_2"
                    position={[-5.78, 12.84, -0.08]}
                    rotation={[1.59, 0.43, 1.49]}
                    userData={{ name: 'mixamorig4:RightShoulder' }}>
                    <group
                      name="mixamorig4RightArm_2"
                      position={[0, 12.24, 0]}
                      rotation={[0.95, -0.07, 0.42]}
                      userData={{ name: 'mixamorig4:RightArm' }}>
                      <group
                        name="mixamorig4RightForeArm_2"
                        position={[0, 20.81, 0]}
                        rotation={[0.02, 0.01, -0.57]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'mixamorig4:RightForeArm' }}>
                        <group
                          name="mixamorig4RightHand_2"
                          position={[0, 27.54, 0]}
                          rotation={[0.1, -0.48, 0]}
                          userData={{ name: 'mixamorig4:RightHand' }}>
                          <group
                            name="mixamorig4RightHandThumb1_2"
                            position={[2.77, 2.84, 1.17]}
                            rotation={[0.09, -0.42, -0.21]}
                            userData={{ name: 'mixamorig4:RightHandThumb1' }}>
                            <group
                              name="mixamorig4RightHandThumb2_2"
                              position={[0.65, 3.25, 0]}
                              rotation={[-0.17, -0.13, -0.06]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:RightHandThumb2' }}>
                              <group
                                name="mixamorig4RightHandThumb3_2"
                                position={[-0.07, 3.12, 0]}
                                rotation={[0.03, 0.18, -0.45]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandThumb3' }}>
                                <group
                                  name="mixamorig4RightHandThumb4_2"
                                  position={[-0.58, 2.57, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandIndex1_2"
                            position={[3.35, 9.01, 0.13]}
                            rotation={[0.17, 0, -0.12]}
                            userData={{ name: 'mixamorig4:RightHandIndex1' }}>
                            <group
                              name="mixamorig4RightHandIndex2_2"
                              position={[0, 3.04, 0]}
                              rotation={[0.47, 0.02, 0.06]}
                              userData={{ name: 'mixamorig4:RightHandIndex2' }}>
                              <group
                                name="mixamorig4RightHandIndex3_2"
                                position={[0, 2.8, 0]}
                                rotation={[0.3, 0.01, 0.01]}
                                userData={{ name: 'mixamorig4:RightHandIndex3' }}>
                                <group
                                  name="mixamorig4RightHandIndex4_2"
                                  position={[0, 2.33, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandMiddle1_2"
                            position={[0.92, 9.25, -0.21]}
                            rotation={[0.38, 0.01, 0.04]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:RightHandMiddle1' }}>
                            <group
                              name="mixamorig4RightHandMiddle2_2"
                              position={[0, 3.24, 0]}
                              rotation={[0.66, 0.03, 0.07]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:RightHandMiddle2' }}>
                              <group
                                name="mixamorig4RightHandMiddle3_2"
                                position={[0, 2.99, 0]}
                                rotation={[0.54, 0.02, 0.05]}
                                userData={{ name: 'mixamorig4:RightHandMiddle3' }}>
                                <group
                                  name="mixamorig4RightHandMiddle4_2"
                                  position={[0, 2.66, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:RightHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandRing1_2"
                            position={[-1.12, 9.28, -0.05]}
                            rotation={[0.69, 0.02, 0.05]}
                            userData={{ name: 'mixamorig4:RightHandRing1' }}>
                            <group
                              name="mixamorig4RightHandRing2_2"
                              position={[0, 2.71, 0]}
                              rotation={[0.41, 0.01, 0.05]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:RightHandRing2' }}>
                              <group
                                name="mixamorig4RightHandRing3_2"
                                position={[0, 2.57, 0]}
                                rotation={[0.35, 0, 0]}
                                userData={{ name: 'mixamorig4:RightHandRing3' }}>
                                <group
                                  name="mixamorig4RightHandRing4_2"
                                  position={[0, 2.19, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandPinky1_2"
                            position={[-3.15, 8.55, 0.1]}
                            rotation={[0.76, 0.03, 0.09]}
                            userData={{ name: 'mixamorig4:RightHandPinky1' }}>
                            <group
                              name="mixamorig4RightHandPinky2_2"
                              position={[0, 2.46, 0]}
                              rotation={[0.85, 0.04, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandPinky2' }}>
                              <group
                                name="mixamorig4RightHandPinky3_2"
                                position={[0, 2.04, 0]}
                                rotation={[0.75, 0.04, 0.03]}
                                userData={{ name: 'mixamorig4:RightHandPinky3' }}>
                                <group
                                  name="mixamorig4RightHandPinky4_2"
                                  position={[0, 1.7, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name="rigLeftUpLeg"
              position={[9.21, -5.49, -0.52]}
              rotation={[-0.35, -0.01, -3.07]}
              scale={[1, 1, 1]}
              userData={{ name: 'rig:LeftUpLeg' }}>
              <group
                name="mixamorig4LeftLeg_2"
                position={[0, 43.52, 0]}
                rotation={[-1.12, -0.02, 0.08]}
                scale={[1, 1, 1]}
                userData={{ name: 'mixamorig4:LeftLeg' }}>
                <group
                  name="mixamorig4LeftFoot_2"
                  position={[-0.14, 36.83, -1.83]}
                  rotation={[1.01, 0.03, 0.04]}
                  scale={[1, 1, 1]}
                  userData={{ name: 'mixamorig4:LeftFoot' }}>
                  <group
                    name="mixamorig4LeftToeBase_2"
                    position={[0.17, 15.83, -1.68]}
                    rotation={[0.59, -0.03, 0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:LeftToeBase' }}>
                    <group
                      name="mixamorig4LeftToe_End_2"
                      position={[0, 4.95, 0]}
                      rotation={[0, 0, 0]}
                      userData={{ name: 'mixamorig4:LeftToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="rigRightUpLeg"
              position={[-9.21, -5.49, -0.46]}
              rotation={[-0.09, -0.21, -3]}
              scale={[1, 1, 1]}
              userData={{ name: 'rig:RightUpLeg' }}>
              <group
                name="mixamorig4RightLeg_2"
                position={[0, 43.52, 0]}
                rotation={[-0.23, -0.03, 0.02]}
                userData={{ name: 'mixamorig4:RightLeg' }}>
                <group
                  name="mixamorig4RightFoot_2"
                  position={[0.14, 36.85, -1.52]}
                  rotation={[1.12, -0.08, -0.17]}
                  userData={{ name: 'mixamorig4:RightFoot' }}>
                  <group
                    name="mixamorig4RightToeBase_2"
                    position={[-0.16, 15.71, -1.88]}
                    rotation={[0.6, 0.04, -0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:RightToeBase' }}>
                    <group
                      name="mixamorig4RightToe_End_2"
                      position={[0, 4.89, 0]}
                      rotation={[0, 0, 0]}
                      scale={[1, 1, 1]}
                      userData={{ name: 'mixamorig4:RightToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="leftTurn"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
          userData={{ name: 'leftTurn' }}>
          <group
            name="mixamorig4Hips_2"
            position={[0.28, 0.44, -94.64]}
            rotation={[-1.59, 0.02, -0.08]}
            userData={{ name: 'mixamorig4:Hips' }}>
            <group
              name="mixamorig4Spine_2"
              position={[0, 9.89, -0.43]}
              rotation={[-0.02, -0.02, 0.04]}
              userData={{ name: 'mixamorig4:Spine' }}>
              <group
                name="mixamorig4Spine1_3"
                position={[0, 11.55, 0]}
                rotation={[0.01, 0, 0.1]}
                scale={[1, 1, 1]}
                userData={{ name: 'mixamorig4:Spine1' }}>
                <group
                  name="mixamorig4Spine2_3"
                  position={[0, 13.2, 0]}
                  rotation={[0.01, 0.01, 0.1]}
                  userData={{ name: 'mixamorig4:Spine2' }}>
                  <group
                    name="mixamorig4Neck_3"
                    position={[0, 14.85, 0]}
                    rotation={[0.06, -0.01, -0.04]}
                    userData={{ name: 'mixamorig4:Neck' }}>
                    <group
                      name="mixamorig4Head_3"
                      position={[0, 7.38, 2.17]}
                      rotation={[0.02, -0.01, -0.04]}
                      userData={{ name: 'mixamorig4:Head' }}>
                      <group
                        name="mixamorig4HeadTop_End_3"
                        position={[0, 21.35, 6.27]}
                        rotation={[0, 0, 0]}
                        userData={{ name: 'mixamorig4:HeadTop_End' }}
                      />
                    </group>
                  </group>
                  <group
                    name="mixamorig4LeftShoulder_3"
                    position={[5.78, 12.84, -0.1]}
                    rotation={[1.73, -0.42, -1.33]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:LeftShoulder' }}>
                    <group
                      name="mixamorig4LeftArm_3"
                      position={[0, 12.24, 0]}
                      rotation={[1.12, -0.05, -0.12]}
                      userData={{ name: 'mixamorig4:LeftArm' }}>
                      <group
                        name="mixamorig4LeftForeArm_3"
                        position={[0, 20.8, 0]}
                        rotation={[0.01, -0.01, 0.25]}
                        userData={{ name: 'mixamorig4:LeftForeArm' }}>
                        <group
                          name="mixamorig4LeftHand_3"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, -0.45, -0.07]}
                          userData={{ name: 'mixamorig4:LeftHand' }}>
                          <group
                            name="mixamorig4LeftHandThumb1_3"
                            position={[-2.82, 2.86, 1.24]}
                            rotation={[0.18, 0.55, 0.32]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandThumb1' }}>
                            <group
                              name="mixamorig4LeftHandThumb2_3"
                              position={[-0.67, 3.3, 0]}
                              rotation={[0.02, -0.28, -0.26]}
                              userData={{ name: 'mixamorig4:LeftHandThumb2' }}>
                              <group
                                name="mixamorig4LeftHandThumb3_3"
                                position={[0.15, 3.11, 0]}
                                rotation={[0.01, -0.05, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandThumb3' }}>
                                <group
                                  name="mixamorig4LeftHandThumb4_3"
                                  position={[0.51, 2.54, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandIndex1_3"
                            position={[-3.27, 9.02, 0.08]}
                            rotation={[0.12, 0.01, 0.02]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandIndex1' }}>
                            <group
                              name="mixamorig4LeftHandIndex2_3"
                              position={[0.01, 3.04, 0]}
                              rotation={[0.36, -0.01, -0.05]}
                              userData={{ name: 'mixamorig4:LeftHandIndex2' }}>
                              <group
                                name="mixamorig4LeftHandIndex3_3"
                                position={[0, 2.82, 0]}
                                rotation={[0.18, 0, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandIndex3' }}>
                                <group
                                  name="mixamorig4LeftHandIndex4_3"
                                  position={[0, 2.47, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandMiddle1_3"
                            position={[-0.91, 9.23, -0.15]}
                            rotation={[0.26, 0, -0.06]}
                            userData={{ name: 'mixamorig4:LeftHandMiddle1' }}>
                            <group
                              name="mixamorig4LeftHandMiddle2_3"
                              position={[0, 3.23, 0]}
                              rotation={[0.58, -0.03, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandMiddle2' }}>
                              <group
                                name="mixamorig4LeftHandMiddle3_3"
                                position={[0, 2.98, 0]}
                                rotation={[0.21, 0, -0.03]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:LeftHandMiddle3' }}>
                                <group
                                  name="mixamorig4LeftHandMiddle4_3"
                                  position={[0, 2.68, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandRing1_3"
                            position={[1.06, 9.06, -0.13]}
                            rotation={[0.45, -0.01, -0.11]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandRing1' }}>
                            <group
                              name="mixamorig4LeftHandRing2_3"
                              position={[0, 2.78, 0]}
                              rotation={[0.7, -0.02, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandRing2' }}>
                              <group
                                name="mixamorig4LeftHandRing3_3"
                                position={[0, 2.68, 0]}
                                rotation={[0.34, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandRing3' }}>
                                <group
                                  name="mixamorig4LeftHandRing4_3"
                                  position={[0, 2.4, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandPinky1_3"
                            position={[3.11, 8.47, 0.1]}
                            rotation={[0.61, -0.03, -0.2]}
                            userData={{ name: 'mixamorig4:LeftHandPinky1' }}>
                            <group
                              name="mixamorig4LeftHandPinky2_3"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, -0.03, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandPinky2' }}>
                              <group
                                name="mixamorig4LeftHandPinky3_3"
                                position={[0, 2.07, 0]}
                                rotation={[0.36, -0.01, -0.05]}
                                userData={{ name: 'mixamorig4:LeftHandPinky3' }}>
                                <group
                                  name="mixamorig4LeftHandPinky4_3"
                                  position={[0, 1.76, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="mixamorig4RightShoulder_3"
                    position={[-5.78, 12.84, -0.08]}
                    rotation={[1.67, 0.43, 1.53]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:RightShoulder' }}>
                    <group
                      name="mixamorig4RightArm_3"
                      position={[0, 12.24, 0]}
                      rotation={[0.84, -0.01, 0.01]}
                      userData={{ name: 'mixamorig4:RightArm' }}>
                      <group
                        name="mixamorig4RightForeArm_3"
                        position={[0, 20.81, 0]}
                        rotation={[0.01, 0.01, -0.31]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'mixamorig4:RightForeArm' }}>
                        <group
                          name="mixamorig4RightHand_3"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, 0.19, 0.22]}
                          userData={{ name: 'mixamorig4:RightHand' }}>
                          <group
                            name="mixamorig4RightHandThumb1_3"
                            position={[2.77, 2.84, 1.17]}
                            rotation={[0.17, -0.55, -0.32]}
                            userData={{ name: 'mixamorig4:RightHandThumb1' }}>
                            <group
                              name="mixamorig4RightHandThumb2_3"
                              position={[0.65, 3.25, 0]}
                              rotation={[0.02, 0.28, 0.29]}
                              userData={{ name: 'mixamorig4:RightHandThumb2' }}>
                              <group
                                name="mixamorig4RightHandThumb3_3"
                                position={[-0.07, 3.12, 0]}
                                rotation={[0.02, 0.05, -0.06]}
                                userData={{ name: 'mixamorig4:RightHandThumb3' }}>
                                <group
                                  name="mixamorig4RightHandThumb4_3"
                                  position={[-0.58, 2.57, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandIndex1_3"
                            position={[3.35, 9.01, 0.13]}
                            rotation={[0.11, -0.01, -0.02]}
                            userData={{ name: 'mixamorig4:RightHandIndex1' }}>
                            <group
                              name="mixamorig4RightHandIndex2_3"
                              position={[0, 3.04, 0]}
                              rotation={[0.36, 0.01, 0.05]}
                              userData={{ name: 'mixamorig4:RightHandIndex2' }}>
                              <group
                                name="mixamorig4RightHandIndex3_3"
                                position={[0, 2.8, 0]}
                                rotation={[0.24, 0, 0]}
                                userData={{ name: 'mixamorig4:RightHandIndex3' }}>
                                <group
                                  name="mixamorig4RightHandIndex4_3"
                                  position={[0, 2.33, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandMiddle1_3"
                            position={[0.92, 9.25, -0.21]}
                            rotation={[0.25, 0, 0.06]}
                            userData={{ name: 'mixamorig4:RightHandMiddle1' }}>
                            <group
                              name="mixamorig4RightHandMiddle2_3"
                              position={[0, 3.24, 0]}
                              rotation={[0.58, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandMiddle2' }}>
                              <group
                                name="mixamorig4RightHandMiddle3_3"
                                position={[0, 2.99, 0]}
                                rotation={[0.28, 0, 0.03]}
                                userData={{ name: 'mixamorig4:RightHandMiddle3' }}>
                                <group
                                  name="mixamorig4RightHandMiddle4_3"
                                  position={[0, 2.66, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandRing1_3"
                            position={[-1.12, 9.28, -0.05]}
                            rotation={[0.44, 0.01, 0.11]}
                            userData={{ name: 'mixamorig4:RightHandRing1' }}>
                            <group
                              name="mixamorig4RightHandRing2_3"
                              position={[0, 2.71, 0]}
                              rotation={[0.7, 0.02, 0.07]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:RightHandRing2' }}>
                              <group
                                name="mixamorig4RightHandRing3_3"
                                position={[0, 2.57, 0]}
                                rotation={[0.31, 0, 0]}
                                userData={{ name: 'mixamorig4:RightHandRing3' }}>
                                <group
                                  name="mixamorig4RightHandRing4_3"
                                  position={[0, 2.19, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:RightHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandPinky1_3"
                            position={[-3.15, 8.55, 0.1]}
                            rotation={[0.6, 0.03, 0.2]}
                            userData={{ name: 'mixamorig4:RightHandPinky1' }}>
                            <group
                              name="mixamorig4RightHandPinky2_3"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandPinky2' }}>
                              <group
                                name="mixamorig4RightHandPinky3_3"
                                position={[0, 2.04, 0]}
                                rotation={[0.39, 0.01, 0]}
                                userData={{ name: 'mixamorig4:RightHandPinky3' }}>
                                <group
                                  name="mixamorig4RightHandPinky4_3"
                                  position={[0, 1.7, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4LeftUpLeg_2"
              position={[9.21, -5.49, -0.52]}
              rotation={[-0.31, 0.19, -2.85]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:LeftUpLeg' }}>
              <group
                name="mixamorig4LeftLeg_3"
                position={[0, 43.52, 0]}
                rotation={[-0.4, -0.16, -0.01]}
                userData={{ name: 'mixamorig4:LeftLeg' }}>
                <group
                  name="mixamorig4LeftFoot_3"
                  position={[-0.14, 36.83, -1.83]}
                  rotation={[1.07, -0.11, 0.02]}
                  scale={[1, 1, 1]}
                  userData={{ name: 'mixamorig4:LeftFoot' }}>
                  <group
                    name="mixamorig4LeftToeBase_3"
                    position={[0.17, 15.83, -1.68]}
                    rotation={[0.57, -0.03, 0.02]}
                    userData={{ name: 'mixamorig4:LeftToeBase' }}>
                    <group
                      name="mixamorig4LeftToe_End_3"
                      position={[0, 4.95, 0]}
                      rotation={[0, 0, 0]}
                      scale={[1, 1, 1]}
                      userData={{ name: 'mixamorig4:LeftToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4RightUpLeg_2"
              position={[-9.21, -5.49, -0.46]}
              rotation={[0.03, -0.07, -2.98]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:RightUpLeg' }}>
              <group
                name="mixamorig4RightLeg_3"
                position={[0, 43.52, 0]}
                rotation={[-0.14, 0.09, 0.11]}
                userData={{ name: 'mixamorig4:RightLeg' }}>
                <group
                  name="mixamorig4RightFoot_3"
                  position={[0.14, 36.85, -1.52]}
                  rotation={[1.16, -0.19, -0.12]}
                  userData={{ name: 'mixamorig4:RightFoot' }}>
                  <group
                    name="mixamorig4RightToeBase_3"
                    position={[-0.16, 15.71, -1.88]}
                    rotation={[0.56, 0.04, -0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:RightToeBase' }}>
                    <group
                      name="mixamorig4RightToe_End_3"
                      position={[0, 4.89, 0]}
                      rotation={[0, 0, 0]}
                      userData={{ name: 'mixamorig4:RightToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="rightTurn"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
          userData={{ name: 'rightTurn' }}>
          <group
            name="mixamorig4Hips_3"
            position={[0.28, 0.44, -94.64]}
            rotation={[-1.59, 0.03, -0.08]}
            userData={{ name: 'mixamorig4:Hips' }}>
            <group
              name="mixamorig4Spine_3"
              position={[0, 9.89, -0.43]}
              rotation={[-0.02, -0.02, 0.04]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:Spine' }}>
              <group
                name="mixamorig4Spine1_4"
                position={[0, 11.55, 0]}
                rotation={[0.01, 0, 0.1]}
                userData={{ name: 'mixamorig4:Spine1' }}>
                <group
                  name="mixamorig4Spine2_4"
                  position={[0, 13.2, 0]}
                  rotation={[0.01, 0.01, 0.1]}
                  userData={{ name: 'mixamorig4:Spine2' }}>
                  <group
                    name="mixamorig4Neck_4"
                    position={[0, 14.85, 0]}
                    rotation={[0.06, -0.01, -0.04]}
                    userData={{ name: 'mixamorig4:Neck' }}>
                    <group
                      name="mixamorig4Head_4"
                      position={[0, 7.38, 2.17]}
                      rotation={[0.02, -0.01, -0.04]}
                      userData={{ name: 'mixamorig4:Head' }}>
                      <group
                        name="mixamorig4HeadTop_End_4"
                        position={[0, 21.35, 6.27]}
                        rotation={[0, 0, 0]}
                        userData={{ name: 'mixamorig4:HeadTop_End' }}
                      />
                    </group>
                  </group>
                  <group
                    name="mixamorig4LeftShoulder_4"
                    position={[5.78, 12.84, -0.1]}
                    rotation={[1.73, -0.42, -1.33]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:LeftShoulder' }}>
                    <group
                      name="mixamorig4LeftArm_4"
                      position={[0, 12.24, 0]}
                      rotation={[1.12, -0.05, -0.12]}
                      userData={{ name: 'mixamorig4:LeftArm' }}>
                      <group
                        name="mixamorig4LeftForeArm_4"
                        position={[0, 20.8, 0]}
                        rotation={[0.01, -0.01, 0.25]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'mixamorig4:LeftForeArm' }}>
                        <group
                          name="mixamorig4LeftHand_4"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, -0.45, -0.07]}
                          userData={{ name: 'mixamorig4:LeftHand' }}>
                          <group
                            name="mixamorig4LeftHandThumb1_4"
                            position={[-2.82, 2.86, 1.24]}
                            rotation={[0.18, 0.55, 0.32]}
                            userData={{ name: 'mixamorig4:LeftHandThumb1' }}>
                            <group
                              name="mixamorig4LeftHandThumb2_4"
                              position={[-0.67, 3.3, 0]}
                              rotation={[0.02, -0.28, -0.26]}
                              userData={{ name: 'mixamorig4:LeftHandThumb2' }}>
                              <group
                                name="mixamorig4LeftHandThumb3_4"
                                position={[0.15, 3.11, 0]}
                                rotation={[0.01, -0.05, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandThumb3' }}>
                                <group
                                  name="mixamorig4LeftHandThumb4_4"
                                  position={[0.51, 2.54, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandIndex1_4"
                            position={[-3.27, 9.02, 0.08]}
                            rotation={[0.12, 0.01, 0.02]}
                            userData={{ name: 'mixamorig4:LeftHandIndex1' }}>
                            <group
                              name="mixamorig4LeftHandIndex2_4"
                              position={[0.01, 3.04, 0]}
                              rotation={[0.36, -0.01, -0.05]}
                              userData={{ name: 'mixamorig4:LeftHandIndex2' }}>
                              <group
                                name="mixamorig4LeftHandIndex3_4"
                                position={[0, 2.82, 0]}
                                rotation={[0.18, 0, -0.01]}
                                userData={{ name: 'mixamorig4:LeftHandIndex3' }}>
                                <group
                                  name="mixamorig4LeftHandIndex4_4"
                                  position={[0, 2.47, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandMiddle1_4"
                            position={[-0.91, 9.23, -0.15]}
                            rotation={[0.26, 0, -0.06]}
                            userData={{ name: 'mixamorig4:LeftHandMiddle1' }}>
                            <group
                              name="mixamorig4LeftHandMiddle2_4"
                              position={[0, 3.23, 0]}
                              rotation={[0.58, -0.03, -0.07]}
                              scale={[1, 1, 1]}
                              userData={{ name: 'mixamorig4:LeftHandMiddle2' }}>
                              <group
                                name="mixamorig4LeftHandMiddle3_4"
                                position={[0, 2.98, 0]}
                                rotation={[0.21, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandMiddle3' }}>
                                <group
                                  name="mixamorig4LeftHandMiddle4_4"
                                  position={[0, 2.68, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandRing1_4"
                            position={[1.06, 9.06, -0.13]}
                            rotation={[0.45, -0.01, -0.11]}
                            scale={[1, 1, 1]}
                            userData={{ name: 'mixamorig4:LeftHandRing1' }}>
                            <group
                              name="mixamorig4LeftHandRing2_4"
                              position={[0, 2.78, 0]}
                              rotation={[0.7, -0.02, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandRing2' }}>
                              <group
                                name="mixamorig4LeftHandRing3_4"
                                position={[0, 2.68, 0]}
                                rotation={[0.34, 0, -0.03]}
                                userData={{ name: 'mixamorig4:LeftHandRing3' }}>
                                <group
                                  name="mixamorig4LeftHandRing4_4"
                                  position={[0, 2.4, 0]}
                                  rotation={[0, 0, 0]}
                                  scale={[1, 1, 1]}
                                  userData={{ name: 'mixamorig4:LeftHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4LeftHandPinky1_4"
                            position={[3.11, 8.47, 0.1]}
                            rotation={[0.61, -0.03, -0.2]}
                            userData={{ name: 'mixamorig4:LeftHandPinky1' }}>
                            <group
                              name="mixamorig4LeftHandPinky2_4"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, -0.03, -0.07]}
                              userData={{ name: 'mixamorig4:LeftHandPinky2' }}>
                              <group
                                name="mixamorig4LeftHandPinky3_4"
                                position={[0, 2.07, 0]}
                                rotation={[0.36, -0.01, -0.05]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:LeftHandPinky3' }}>
                                <group
                                  name="mixamorig4LeftHandPinky4_4"
                                  position={[0, 1.76, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:LeftHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="mixamorig4RightShoulder_4"
                    position={[-5.78, 12.84, -0.08]}
                    rotation={[1.67, 0.43, 1.53]}
                    userData={{ name: 'mixamorig4:RightShoulder' }}>
                    <group
                      name="mixamorig4RightArm_4"
                      position={[0, 12.24, 0]}
                      rotation={[0.84, -0.01, 0.01]}
                      userData={{ name: 'mixamorig4:RightArm' }}>
                      <group
                        name="mixamorig4RightForeArm_4"
                        position={[0, 20.81, 0]}
                        rotation={[0.01, 0.01, -0.31]}
                        userData={{ name: 'mixamorig4:RightForeArm' }}>
                        <group
                          name="mixamorig4RightHand_4"
                          position={[0, 27.54, 0]}
                          rotation={[0.2, 0.19, 0.22]}
                          scale={[1, 1, 1]}
                          userData={{ name: 'mixamorig4:RightHand' }}>
                          <group
                            name="mixamorig4RightHandThumb1_4"
                            position={[2.77, 2.84, 1.17]}
                            rotation={[0.17, -0.55, -0.32]}
                            userData={{ name: 'mixamorig4:RightHandThumb1' }}>
                            <group
                              name="mixamorig4RightHandThumb2_4"
                              position={[0.65, 3.25, 0]}
                              rotation={[0.02, 0.28, 0.29]}
                              userData={{ name: 'mixamorig4:RightHandThumb2' }}>
                              <group
                                name="mixamorig4RightHandThumb3_4"
                                position={[-0.07, 3.12, 0]}
                                rotation={[0.02, 0.05, -0.06]}
                                userData={{ name: 'mixamorig4:RightHandThumb3' }}>
                                <group
                                  name="mixamorig4RightHandThumb4_4"
                                  position={[-0.58, 2.57, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandThumb4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandIndex1_4"
                            position={[3.35, 9.01, 0.13]}
                            rotation={[0.11, -0.01, -0.02]}
                            userData={{ name: 'mixamorig4:RightHandIndex1' }}>
                            <group
                              name="mixamorig4RightHandIndex2_4"
                              position={[0, 3.04, 0]}
                              rotation={[0.36, 0.01, 0.05]}
                              userData={{ name: 'mixamorig4:RightHandIndex2' }}>
                              <group
                                name="mixamorig4RightHandIndex3_4"
                                position={[0, 2.8, 0]}
                                rotation={[0.24, 0, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandIndex3' }}>
                                <group
                                  name="mixamorig4RightHandIndex4_4"
                                  position={[0, 2.33, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandIndex4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandMiddle1_4"
                            position={[0.92, 9.25, -0.21]}
                            rotation={[0.25, 0, 0.06]}
                            userData={{ name: 'mixamorig4:RightHandMiddle1' }}>
                            <group
                              name="mixamorig4RightHandMiddle2_4"
                              position={[0, 3.24, 0]}
                              rotation={[0.58, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandMiddle2' }}>
                              <group
                                name="mixamorig4RightHandMiddle3_4"
                                position={[0, 2.99, 0]}
                                rotation={[0.28, 0, 0.03]}
                                userData={{ name: 'mixamorig4:RightHandMiddle3' }}>
                                <group
                                  name="mixamorig4RightHandMiddle4_4"
                                  position={[0, 2.66, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandMiddle4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandRing1_4"
                            position={[-1.12, 9.28, -0.05]}
                            rotation={[0.44, 0.01, 0.11]}
                            userData={{ name: 'mixamorig4:RightHandRing1' }}>
                            <group
                              name="mixamorig4RightHandRing2_4"
                              position={[0, 2.71, 0]}
                              rotation={[0.7, 0.02, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandRing2' }}>
                              <group
                                name="mixamorig4RightHandRing3_4"
                                position={[0, 2.57, 0]}
                                rotation={[0.31, 0, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandRing3' }}>
                                <group
                                  name="mixamorig4RightHandRing4_4"
                                  position={[0, 2.19, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandRing4' }}
                                />
                              </group>
                            </group>
                          </group>
                          <group
                            name="mixamorig4RightHandPinky1_4"
                            position={[-3.15, 8.55, 0.1]}
                            rotation={[0.6, 0.03, 0.2]}
                            userData={{ name: 'mixamorig4:RightHandPinky1' }}>
                            <group
                              name="mixamorig4RightHandPinky2_4"
                              position={[0, 2.46, 0]}
                              rotation={[0.79, 0.03, 0.07]}
                              userData={{ name: 'mixamorig4:RightHandPinky2' }}>
                              <group
                                name="mixamorig4RightHandPinky3_4"
                                position={[0, 2.04, 0]}
                                rotation={[0.39, 0.01, 0]}
                                scale={[1, 1, 1]}
                                userData={{ name: 'mixamorig4:RightHandPinky3' }}>
                                <group
                                  name="mixamorig4RightHandPinky4_4"
                                  position={[0, 1.7, 0]}
                                  rotation={[0, 0, 0]}
                                  userData={{ name: 'mixamorig4:RightHandPinky4' }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4LeftUpLeg_3"
              position={[9.21, -5.49, -0.52]}
              rotation={[-0.31, 0.19, -2.85]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:LeftUpLeg' }}>
              <group
                name="mixamorig4LeftLeg_4"
                position={[0, 43.52, 0]}
                rotation={[-0.4, -0.16, -0.01]}
                userData={{ name: 'mixamorig4:LeftLeg' }}>
                <group
                  name="mixamorig4LeftFoot_4"
                  position={[-0.14, 36.83, -1.83]}
                  rotation={[1.07, -0.11, 0.02]}
                  userData={{ name: 'mixamorig4:LeftFoot' }}>
                  <group
                    name="mixamorig4LeftToeBase_4"
                    position={[0.17, 15.83, -1.68]}
                    rotation={[0.57, -0.03, 0.02]}
                    scale={[1, 1, 1]}
                    userData={{ name: 'mixamorig4:LeftToeBase' }}>
                    <group
                      name="mixamorig4LeftToe_End_4"
                      position={[0, 4.95, 0]}
                      rotation={[0, 0, 0]}
                      scale={[1, 1, 1]}
                      userData={{ name: 'mixamorig4:LeftToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="mixamorig4RightUpLeg_3"
              position={[-9.21, -5.49, -0.46]}
              rotation={[0.03, -0.07, -2.98]}
              scale={[1, 1, 1]}
              userData={{ name: 'mixamorig4:RightUpLeg' }}>
              <group
                name="mixamorig4RightLeg_4"
                position={[0, 43.52, 0]}
                rotation={[-0.14, 0.09, 0.11]}
                userData={{ name: 'mixamorig4:RightLeg' }}>
                <group
                  name="mixamorig4RightFoot_4"
                  position={[0.14, 36.85, -1.52]}
                  rotation={[1.16, -0.19, -0.12]}
                  userData={{ name: 'mixamorig4:RightFoot' }}>
                  <group
                    name="mixamorig4RightToeBase_4"
                    position={[-0.16, 15.71, -1.88]}
                    rotation={[0.57, 0.04, -0.02]}
                    userData={{ name: 'mixamorig4:RightToeBase' }}>
                    <group
                      name="mixamorig4RightToe_End_4"
                      position={[0, 4.89, 0]}
                      rotation={[0, 0, 0]}
                      userData={{ name: 'mixamorig4:RightToe_End' }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    </>
  )
}

export default Model; 

useGLTF.preload('/Player.glb')

